--- 
- name: checking connection
  hosts: cart-dev.roboshop-internal
  become: yes
  tasks:
    - name: installing git
      ansible.builtin.package:
        name: git
        state: present

    - name: 