- name: clonning repo url
  hosts: all
  become: yes
  tasks:
    - name: install git 
      ansible.builtin.package:
        name: git
        state: present

    - name: Clone the repository
      git:
        repo: "git@github.com:premsarja/ans-1.git"
        dest: "/home/ec2-user/"  
        version: main 
        update: yes  
