---
- name: condition
  hosts: mongodb-dev.roboshop-internal
  vars:
    action: true
  tasks:

    - name: run if flavor is CentOS
      ansible.builtin.debug:
        msg: "Welcome to CentOS {{ ansible_distribution }}"
      when: ansible_distribution == "CentOS"

    - name: run if flavor is redhat
      ansible.builtin.debug:
        msg: "Welcome to redhat {{ ansible_distribution }}"
      when: ansible_distribution == "redhat"