---
- name: condition
  hosts: mongodb-dev.roboshop-internal
  vars:
    action: true
  tasks:
    - name: run if flavour is CentOS
      ansible.builtin.debug:
        msg: welcome to CentOS
      when: ansible_distribution == "CentOS"     

    - name: run if flavour is redhat
      ansible.builtin.debug:
        msg: welcome to redhat
      when: ansible_distribution == "redhat"       