---
- name: Install SonarQube
  hosts: all
  become: yes
  tasks:
    - name: Ensure Java is installed
      package:
        name: java
        state: present
        
    - name: Create /opt directory
      ansible.builtin.file:
        path: /opt
        state: directory
        
    - name: Download SonarQube zip file
      ansible.builtin.get_url:
        url: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.6.1.59531.zip"
        dest: "/opt/sonarqube-9.6.1.59531.zip"
        

    - name: Unzip SonarQube
      ansible.builtin.unarchive:
        src: "/opt/sonarqube-9.6.1.59531.zip"
        dest: "/opt/"
        remote_src: yes

    - name: Creating user
      ansible.builtin.user:
        name: sonar
        comment: sonar user
      register: USERINFO 
    
    - name: Printing the variable 
      ansible.builtin.debug:
        msg: Value of the OUT is {{USERINFO}}            
    
    