---
- name: Install SonarQube
  hosts: all
  become: yes
  tasks:
    - name: Ensure Java is installed
      package:
        name: openjdk-11-jdk
        state: present
        
    - name: Create /opt directory
      ansible.builtin.file:
        path: /opt
        state: directory
        
    - name: Download SonarQube zip file
      ansible.builtin.get_url:
        url: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.6.1.59531.zip"
        dest: "/opt/sonarqube-9.6.1.59531.zip"
