- name: Install SonarQube
  hosts: all
  become: yes
  tasks:
    - name: Ensure Java is installed
      package:
        name: java  # Package name for OpenJDK 11, adjust based on your OS and Java version
        state: present
        
    - name: SonarQube
      ansible.builtin.unarchive:
        src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.6.1.59531.zip
        dest: /opt/sonarqube-9.6.1.59531.zip
        remote_src: no