---
- name: Playbook using the role
  hosts: all
  become: yes
  
  tasks:
    - name: clonning repo url
      become: yes
      hosts: all
      tasks:
        - name: install git 
          ansible.builtin.package:
            name: git
            state: present
